### PR TITLE
added gluon in PYTHONPATH because env needs it when importing gluon modu...

### PR DESCRIPTION
**Pull request by suzanshakya**
...les

### CODE REVIEW

**Comment by niphlod** [comment]
why gluon is needed ? when you import modules you should do

```
import gluon.something
```

or

```
from gluon.something import whatever
```

instead of 

```
import something
```

**Comment by 0o-de-lally** [comment]
Backing up Suzan's commit. There was an issue with scheduler. Would be nice to see an implementation of behavioral and scheduler.

**Comment by niphlod** [comment]
it's not a problem of trust, I just wanted to know where the problem was :-P

**Comment by 0o-de-lally** [comment]
:) should welcome augmented have a dummy scheduler function to test this
case?

**Comment by niphlod** [comment]
I'm thinking on the general architecture, and as a matter of fact I envisioned welcome_augmented like a sort of app where everybody can contribute with their own tests on "general" features...this means I'll probably figure out a way to test the scheduler API, but if you're trying to test instead a function that you usually put in a queue , it will be faster to test the function itself than the scheduler itself...

**Comment by 0o-de-lally** [comment]
Agreed, its better to test the function. But our case is: to have an
end-to-end test. User takes an action, which requires a queue, test the
response from the queue.
Btw we never got to that point, because behave complained about not having
the scheduler module, before running tests.

Lucas Geiger

**Comment by niphlod** [comment]
that's what pretty much was my point in the first place: can you ship me a piece of code to test it ? without knowing what you're trying to do it's difficult to know what's the best way to fix it.

**Comment by 0o-de-lally** [comment]
I'm not sure what's the best way to give you something simple to
troubleshoot.
We may be importing incorrectly, so we will check first.
I think its related to
https://groups.google.com/forum/m/#!topic/web2py-developers/Yf-atiE3Yls

**Comment by niphlod** [comment]
I know what the scheduler does but adding gluon to sys.path shouldn't be the answer. moreover, seems that the scheduler just "misplaces" the path, while in your case you want to add a path that shouldn't be useful unless you do imports a-la

```
import storage
```

instead of

```
from gluon import storage
```

**Comment by niphlod** [comment]
if you can, please test the scheduler with this patch applied and see if everything works out.
https://github.com/web2py/web2py/pull/158

**Comment by 0o-de-lally** [comment]
Works fine with loading the server and manually testing.
But behavioural still complains without
@suzanshakyahttps://github.com/suzanshakya's patch,
see below.
I'm sending you a private message with a parallel issue with import and
scheduler.

Traceback (most recent call last):
  File "web2py_tip/gluon/restricted.py", line 212, in restricted
    exec ccode in environment
  File "/web2py_tip/applications/keyscores/models/db_task.py", line 2, in
<module>
    import scheduler
  File "/web2py_tip/gluon/custom_import.py", line 81, in custom_importer
    raise ImportError, 'Cannot import module %s' % str(e)
ImportError: Cannot import module 'scheduler'

Lucas Geiger

**Comment by niphlod** [comment]
here's exactly the error I told you about .... scheduler needs to be imported from gluon, as documented.

```
 from gluon.scheduler import Scheduler
 scheduler = Scheduler(db)
```

seems instead that you're using the old way to import gluon modules (line 2 in db_task.py), that is to skip the gluon prefix: this is allowed for historical reason but we're trying to leave that back, and since both scheduler and welcome_augmented are relatively new projects, you **should** use the documented way and not the old one.

**Comment by 0o-de-lally** [comment]
OK thanks for effort looking at this. Where's the new documentation on this?

here's exactly the error I told you about .... scheduler needs to be
imported from gluon, as documented.

 from gluon.scheduler import Scheduler
 scheduler = Scheduler(db)

seems instead that you're using the old way to import gluon modules (line 2
in db_task.py), that is to skip the gluon prefix: this is allowed for
historical reason but we're trying to leave that back, and since both
scheduler and welcome_augmented are relatively new projects, you
_should_use the documented way and not the old one.

—
Reply to this email directly or view it on
GitHubhttps://github.com/niphlod/welcome_augmented/pull/2#issuecomment-22058914
.

**Comment by niphlod** [comment]
it's on the docstring on the module itself, on the book at the scheduler section and also in the w2p_scheduler_tests app... don't know where you took the

```
import scheduler
```

bit. AFAIK, it has never been on any piece of docs.

**Pull request closed without merging**
